using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FlowWire.Framework.Analyzers.Generators;

[Generator]
public class AssemblyMarkerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        /// <summary>
        /// Generates a marker attribute for the assembly.
        /// </summary>
        context.RegisterPostInitializationOutput(ctx =>
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using FlowWire.Framework.Abstractions;");
            sb.AppendLine();
            sb.AppendLine("[assembly: FlowWireAssembly]");

            ctx.AddSource("FlowWireAssemblyMarker.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }
}
